name: PR- Continuous Integration Build

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

        #      - name: Validate composer.json and composer.lock
        #        run: composer validate

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --ignore-platform-reqs

      - name: Moving build to artifacts directory
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_COMMENT_HREF: ${{ github.event.pull_request._links.comments.href }}
          PR_LABEL_HREF: ${{ github.event.pull_request._links.issue.href }}/labels
          PR_SHA: ${{ github.event.after }}
          PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
        run: bash build.sh

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
#      - name: Dump job context
#        env:
#          JOB_CONTEXT: ${{ toJson(job) }}
#        run: echo "$JOB_CONTEXT"
#      - name: Dump steps context
#        env:
#          STEPS_CONTEXT: ${{ toJson(steps) }}
#        run: echo "$STEPS_CONTEXT"
#      - name: Dump runner context
#        env:
#          RUNNER_CONTEXT: ${{ toJson(runner) }}
#        run: echo "$RUNNER_CONTEXT"
#      - name: Dump strategy context
#        env:
#          STRATEGY_CONTEXT: ${{ toJson(strategy) }}
#        run: echo "$STRATEGY_CONTEXT"
#      - name: Dump matrix context
#        env:
#          MATRIX_CONTEXT: ${{ toJson(matrix) }}
#        run: echo "$MATRIX_CONTEXT"
